"""
Pydantic models for Charlie's knowledge graph nodes and edges.

These models extend graphiti's base models with UI-specific properties
and methods for rendering in the web interface.
"""

from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field, computed_field
import re


class EpisodicNode(BaseModel):
    """
    Represents a journal entry (Episodic node) from the knowledge graph.

    Maps to Kuzu's Episodic node with additional UI helpers.
    """

    uuid: str
    name: str
    content: str
    valid_at: datetime
    created_at: datetime

    @computed_field
    @property
    def title(self) -> str:
        """
        Extract title from markdown content or generate fallback.

        Tries to find first markdown header, falls back to hash suffix,
        then to generic "Untitled Entry".
        """
        match = re.match(r"^#\s+(.+)$", self.content, re.MULTILINE)
        if match:
            return match.group(1).strip()

        if self.name.startswith("journal_"):
            hash_suffix = self.name[8:16]
            return f"Entry {hash_suffix}"

        return "Untitled Entry"

    @computed_field
    @property
    def display_date(self) -> str:
        """Format valid_at date for display."""
        return self.valid_at.strftime("%B %d, %Y at %I:%M %p")

    @computed_field
    @property
    def preview(self) -> str:
        """Generate preview text (first 200 chars, no markdown headers)."""
        lines = self.content.split("\n")
        text_lines = [line for line in lines if not line.strip().startswith("#")]
        preview_text = " ".join(text_lines)
        preview_text = preview_text.strip()[:200]
        if len(self.content) > 200:
            preview_text += "..."
        return preview_text


class EntityNode(BaseModel):
    """
    Represents an entity (person, place, concept) from the knowledge graph.

    Maps to Kuzu's Entity node with additional UI helpers.
    """

    uuid: str
    name: str
    summary: Optional[str] = None
    created_at: datetime

    @computed_field
    @property
    def display_summary(self) -> str:
        """Return summary or fallback message."""
        return self.summary if self.summary else "No summary available"


class RelationshipNode(BaseModel):
    """
    Represents a relationship between entities (RelatesToNode_).

    This is the hypernode pattern used by graphiti to store relationship facts.
    """

    uuid: str
    name: str
    fact: str
    valid_at: datetime
    invalid_at: Optional[datetime] = None
    created_at: datetime
    expired_at: Optional[datetime] = None
    episodes: List[str] = Field(default_factory=list)

    @computed_field
    @property
    def is_valid(self) -> bool:
        """Check if relationship is currently valid."""
        return self.invalid_at is None or self.invalid_at > datetime.now()

    @computed_field
    @property
    def source_episodes_count(self) -> int:
        """Count of source episodes for this relationship."""
        return len(self.episodes)


class CommunityNode(BaseModel):
    """
    Represents a community (cluster of related entities).

    Communities are generated by the Leiden algorithm and group
    strongly connected entities together.
    """

    uuid: str
    name: str
    summary: Optional[str] = None
    created_at: datetime
    member_count: Optional[int] = None

    @computed_field
    @property
    def display_summary(self) -> str:
        """Return summary or fallback message."""
        return self.summary if self.summary else "No summary available"


class MentionsEdge(BaseModel):
    """
    Represents a MENTIONS relationship between Episode and Entity.
    """

    created_at: datetime


class EntityMention(BaseModel):
    """
    Entity with mention metadata, used in episode detail views.
    """

    entity: EntityNode
    mention_count: int = 1


class EpisodeWithEntities(BaseModel):
    """
    Episode enriched with its mentioned entities.
    """

    episode: EpisodicNode
    entities: List[EntityNode] = Field(default_factory=list)


class EntityContext(BaseModel):
    """
    A context where an entity was mentioned.

    Includes the source episode and an excerpt showing the mention.
    """

    episode_uuid: str
    episode_title: str
    episode_date: datetime
    excerpt: str


class EntityWithContexts(BaseModel):
    """
    Entity enriched with source contexts.
    """

    entity: EntityNode
    contexts: List[EntityContext] = Field(default_factory=list)


class RelatedEntity(BaseModel):
    """
    Entity related to another entity through a relationship.
    """

    entity: EntityNode
    relationship: RelationshipNode


class CommunityMember(BaseModel):
    """
    Entity that belongs to a community with additional metadata.
    """

    entity: EntityNode
    episode_count: int = 0


class CommunityDetail(BaseModel):
    """
    Community with its member entities.
    """

    community: CommunityNode
    members: List[CommunityMember] = Field(default_factory=list)
    member_count: int = 0


class EpisodeWithMentionCount(BaseModel):
    """
    Episode with count of how many community entities are mentioned.
    """

    episode: EpisodicNode
    entity_mention_count: int = 0


class CommunityWithEpisodes(BaseModel):
    """
    Community with episodes that mention its member entities.
    """

    community: CommunityNode
    episodes: List[EpisodeWithMentionCount] = Field(default_factory=list)
    episode_count: int = 0
